version: '3.8'
services:

  mongodb:
    container_name: github-scraper_mongodb-dev
    volumes:
      - dev-mongodb-github:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  github-scraper:
    container_name: github-scraper-dev
    environment:
      - DEV_RUN

volumes:
  dev-mongodb-github:
    external:
      name: dev-mongodb-github
