version: '3.8'
services:

  mongodb:
    container_name: github-stats-mongodb
    expose:
      - 27017
    volumes:
      - mongodb-github-stats:/data/db
    restart: unless-stopped
    networks:
      - github-stats-network
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.labels.main-node == true

  scraper:
    container_name: github-stats-scraper
    image: gordonpn/github-stats-scraper:latest
    networks:
      - github-stats-network
    restart: unless-stopped
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  backend:
    container_name: github-stats-backend
    image: gordonpn/github-stats-backend:latest
    networks:
      - github-stats-network
    restart: unless-stopped
    expose:
      - 5000
    healthcheck:
      test: curl --fail -s http://localhost:8080/api/v1/healthcheck || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    container_name: github-stats-frontend
    image: gordonpn/github-stats-frontend:latest
    environment:
      - NODE_ENV=production
    networks:
      - github-stats-network
    restart: unless-stopped
    expose:
      - 3000
    volumes:
      - caddy-github:/data
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  proxy:
    container_name: github-stats-proxy
    image: gordonpn/github-stats-proxy:stable
    networks:
      - traefik-public
      - github-stats-network
    restart: unless-stopped
    expose:
      - 80
    healthcheck:
      test: curl --fail -s http://localhost:80/health || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 1m30s
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.services.github.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

volumes:
  caddy-hotdeals:
    name: caddy-github
  mongodb-github-stats:
    external:
      name: mongodb-github-stats

networks:
  github-stats-network:
    driver: overlay
  traefik-public:
    external: true
    driver: overlay
