version: '3.8'
services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_ROLE=readWrite
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
      - GITHUB_TOKEN
      - HC_UUID
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
    depends_on:
      - backend
      - mongodb

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
    depends_on:
      - frontend
      - backend
