version: '3.8'
services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_ROLE=readWrite
      - MONGO_NON_ROOT_USERNAME
      - MONGO_NON_ROOT_PASSWORD
      - TZ=America/Montreal
    volumes:
      - ./.docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  github-scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    environment:
      - TZ=America/Montreal
      - MONGO_INITDB_DATABASE
      - MONGO_NON_ROOT_PASSWORD
      - MONGO_NON_ROOT_USERNAME
      - GITHUB_TOKEN
      - HC_UUID
    depends_on:
      - mongodb
